FROM node:20-alpine3.18

WORKDIR /usr/src/app

COPY package*.json .

RUN npm install

COPY . .

RUN npx nx build  order


FROM node:20-alpine3.18

WORKDIR /usr/src/app

COPY package*.json .

RUN npm install --omit=dev

COPY --from=0 /usr/src/app/dist .

EXPOSE 3001

RUN npm install pm2 -g

CMD [ "pm2-runtime", "apps/order/main.js" ]
