FROM node:20-alpine3.18

WORKDIR /usr/src/app

COPY package*.json .

RUN npm install

COPY . .

RUN npx nx build  user


FROM node:20-alpine3.18

WORKDIR /usr/src/app

COPY package*.json .

RUN npm install --omit=dev

COPY --from=0 /usr/src/app/dist .

COPY --from=0 /usr/src/app/apps/user/src/user.swagger.yaml ./apps/user

EXPOSE 3003

RUN npm install pm2 -g

CMD [ "pm2-runtime", "apps/user/main.js" ]
